# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchQuery',
            fields=[
                ('study_title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('num_docs', models.IntegerField(default=0, verbose_name='number of documents')),
                ('successes', models.IntegerField(default=0, verbose_name='successful classifications')),
                ('fails', models.IntegerField(default=0, verbose_name='false classifications')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cFem', models.IntegerField(default=0, verbose_name='classified Female')),
                ('cMale', models.IntegerField(default=0, verbose_name='classified Male')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoAmI.ResearchQuery')),
            ],
        ),
    ]
