# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoAmI', '0002_auto_20161005_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='cFem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='cMale',
            field=models.IntegerField(default=0),
        ),
    ]
