# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reflection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_docs', models.IntegerField(default=0, verbose_name='number of documents')),
                ('successes', models.IntegerField(default=0, verbose_name='successful classifications')),
                ('fails', models.IntegerField(default=0, verbose_name='false classifications')),
                ('study_title', models.ForeignKey(default='Gender Perception of Gender', on_delete=django.db.models.deletion.CASCADE, to='reflection.ResearchProposals')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cFem', models.IntegerField(default=0, verbose_name='classified Female')),
                ('cMale', models.IntegerField(default=0, verbose_name='classified Male')),
                ('study', models.ForeignKey(default='Gender Perception of Gender', on_delete=django.db.models.deletion.CASCADE, to='genPerGen.ResearchQuery')),
            ],
        ),
    ]
