# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProposals',
            fields=[
                ('proposal', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('detail', models.TextField()),
                ('status', models.BooleanField(default=False, verbose_name='approval_status')),
                ('alias', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicAreas',
            fields=[
                ('topic_area', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('detail', models.TextField()),
                ('status', models.BooleanField(default=False, verbose_name='approval_status')),
                ('alias', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='researchproposals',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflection.TopicAreas'),
        ),
    ]
