# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-20 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproposals',
            name='alias',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='topicareas',
            name='alias',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
